# Install script for directory: /home/einar/px4_firmware/src/Firmware

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/drivers/led/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/drivers/device/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/drivers/boards/sitl/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/drivers/pwm_out_sim/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/drivers/rgbled/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/platforms/common/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/platforms/posix/px4_layer/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/platforms/posix/work_queue/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/platforms/posix/drivers/adcsim/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/platforms/posix/drivers/gpssim/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/platforms/posix/drivers/tonealrmsim/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/platforms/posix/drivers/accelsim/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/platforms/posix/drivers/airspeedsim/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/platforms/posix/drivers/barosim/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/platforms/posix/drivers/gyrosim/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/systemcmds/param/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/systemcmds/mixer/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/systemcmds/ver/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/systemcmds/esc_calib/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/systemcmds/reboot/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/systemcmds/topic_listener/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/uORB/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/param/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/systemlib/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/systemlib/mixer/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/sensors/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/simulator/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/mavlink/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/attitude_estimator_ekf/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/attitude_estimator_q/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/ekf_att_pos_estimator/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/position_estimator_inav/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/navigator/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/mc_pos_control/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/mc_att_control/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/mc_pos_control_multiplatform/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/mc_att_control_multiplatform/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/land_detector/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/fw_att_control/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/fw_pos_control_l1/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/dataman/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/sdlog2/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/commander/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/modules/controllib/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/lib/mathlib/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/lib/mathlib/math/filter/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/lib/conversion/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/lib/ecl/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/lib/external_lgpl/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/lib/geo/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/lib/geo_lookup/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/lib/launchdetection/cmake_install.cmake")
  include("/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/src/firmware/posix/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home/einar/px4_firmware/src/Firmware/build_posix_sitl_simple/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
